name: mdwp
favicon: null
layout_spectrum: 0.75816
typography_spectrum: 0.23776
title: 'mdwp - Digital Consulting & Services'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0502'
    - '#ffffff'
    - '#818d97'
    - '#c8b999'
    - '#3f3f3d'
  brandStrength: 0
  lightness: 0.42539161583408713
  saturation: 0.23519253358244896
  rhythmicContrast: 1
purpose: []
