name: mdwp
favicon: null
layout_spectrum: 0.35249
typography_spectrum: 0.23776
title: 'mdwp - Digital Consulting & Services'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9e122d'
    - '#ecf1af'
    - '#020401'
    - '#26441e'
    - '#63bc4e'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
