name: mdwp
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23776
title: 'mdwp - Digital Consulting & Services'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222330'
    - '#5c8ad0'
    - '#5f5348'
    - '#ffeaab'
    - '#e2b27a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
